---
title: "index"
author: "MMLut"
date: "2026-02-25"
output: html_document
---

```{r setup, warning=FALSE, message=FALSE, include=FALSE}
library(compmus)
library(readr)
library(tidyr)
library(dplyr)
library(purrr)
library(ggplot2)
```

## Week 9
```{r pressure, warning=FALSE, message=FALSE, echo=FALSE, cache=TRUE}
make_timbre_similarity_plot <- function(FileName, step = 50L, title = NULL) {
  read_csv(FileName, show_col_types = FALSE) |>
  compmus_wrangle_timbre() |> 
  filter(row_number() %% step == 0L) |> 
  mutate(timbre = map(timbre, compmus_normalise, "euclidean")) |>
  compmus_self_similarity(timbre, "cosine") |> 
  ggplot(
    aes(
      x = xstart + xduration / 2,
      width = step * xduration,
      y = ystart + yduration / 2,
      height = step * yduration,
      fill = d
    )
  ) +
  geom_tile() +
  coord_fixed() +
  scale_fill_viridis_c(guide = "none") +
  theme_classic() +
  labs(x = "", y = "")
}
make_chroma_distance_plot <- function(
  data1,
  data2,
  label1 = "",
  label2 = "",
  title = NULL,
  step = 50L,
  norm_method = "chebyshev",
  dist_method = "euclidean"
) {
  
  d1 <- data1 |>
    compmus_wrangle_chroma() |> 
    mutate(pitches = map(pitches, compmus_normalise, norm_method)) |> 
    filter(row_number() %% step == 0L)
  
  d2 <- data2 |>
    compmus_wrangle_chroma() |> 
    mutate(pitches = map(pitches, compmus_normalise, norm_method)) |> 
    filter(row_number() %% step == 0L)
  
  compmus_long_distance(
    d1,
    d2,
    feature = pitches,
    method = dist_method
  ) |>
    filter(!is.nan(d)) |> 
    ggplot(
      aes(
        x = xstart + xduration / 2,
        width = step * xduration,
        y = ystart + yduration / 2,
        height = step * yduration,
        fill = d
      )
    ) +
    geom_tile() +
    coord_equal() +
    labs(title = title, x = label1, y = label2) +
    theme_minimal() +
    scale_fill_viridis_c(guide = NULL)
}


p <- make_timbre_similarity_plot("heal_cep.csv", title = "Heal: Cepstrogram Self窶全imilarity")
p
p <- make_chroma_distance_plot(read_csv("heal_chrom.csv", show_col_types = FALSE), read_csv("heal_chrom.csv", show_col_types = FALSE), label1 = "heal", label2 = "heal", title = "Heal: Cepstrogram Self窶全imilarity")
p
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, cache=TRUE}
p <- make_timbre_similarity_plot("4ui_cep.csv", title = "4ui12: Cepstrogram Self窶全imilarity")
p
p <- make_chroma_distance_plot(read_csv("4ui_chrom.csv", show_col_types = FALSE), read_csv("4ui_chrom.csv", show_col_types = FALSE), label1 = "4ui12", label2 = "4ui12", title = "4ui12: Cepstrogram Self窶全imilarity")
p
```
Didn't quite have time for the text yet, will be here before 12:00 28-02